---
title: "Hospital Presentation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1) 



I then made a simple histogram of the 30-day death rates from heart attacks:

```{r warning = F}
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11], main = "Histogram of 30-day Heart Attack Death Rates", xlab = "Rate", ylab = "frequency")
```


## 2) The "Best" Function

I started by writing a function called best to return the best hospital for a user inputted outcome and state.

```{r}
best <- function(state, outcome){
  data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
  StateChecker <- unique(data[, "State"])
  if(!(state %in% StateChecker)){stop("Invalid State!")}
  if(outcome == "heart attack"||outcome == "Heart Attack"){outcome = 11}
  if(outcome == "heart failure"||outcome == "Heart Failure"){outcome = 17}
  if(outcome == "pneumonia"||outcome == "Pneumonia"){outcome = 23}
  if(!is.numeric(outcome)){stop("Invalid Outcome!")}
  minpos <- NA
  x <- subset(data, State == state)
  x <- x[order(as.numeric(x[, outcome])), ]
  return (x[1, "Hospital.Name"])
}
```

Here is some example output from the function:

```{r}
best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
```


## 3) The "rankhospital" Function

I then wrote a function to 